### ISSUE TITLE
restart docker after proxy

### ISSUE THREAD

**Issue by bsmeding** [bsmeding/ansible_role_docker#2]
after set htt-proxy.conf, do daemon-reload and restart service so the settings are applied

**Comment by bsmeding** [comment]
reopen need investigation

**Comment by bsmeding** [comment]
added:
```
    - name: Set docker http-proxy.conf (older version before 23)
      ansible.builtin.template:
        src: http-proxy.conf.j2
        dest: "/etc/systemd/system/docker.service.d/http-proxy.conf"
      notify: restart docker
```
